### ISSUE TITLE
Swiftcast Interaction

### ISSUE THREAD

**Issue by CatXIV** [Tylian/rdm#10]
Encountered a possible minor issue, although it may not be an issue if the behavior of Swiftcast has changed in 4.0 to match what we have seen of Dualcast.

In the simulator, if under the effect of Swiftcast, the effect will fade upon the execution of a weaponskill in the same way Dualcast fades. At least as of 3.5, Swiftcast doesn't fade when using a weaponskill which can be tested by adding Swiftcast as a cross class skill to any melee class (not job). I haven't managed to catch any footage of a Red Mage using a weaponskill while Swiftcast was in effect so it's possible the behavior has changed. It will be something to test once 4.0 goes live.

Also a couple related observations that would need verification to determine if they are issues. If you have both Dualcast and Swiftcast active when executing a weaponskill, Swiftcast will fade while Dualcast remains which seemed a little strange. The same behavior will happen if you have Dualcast and Swiftcast active upon the casting of a spell, consuming Swiftcast while leaving Dualcast in effect for use with another spell, but that could be an indented interaction.

**Comment by Tylian** [comment]
> In the simulator, if under the effect of Swiftcast, the effect will fade upon the execution of a weaponskill in the same way Dualcast fades. At least as of 3.5, Swiftcast doesn't fade when using a weaponskill which can be tested by adding Swiftcast as a cross class skill to any melee class (not job). I haven't managed to catch any footage of a Red Mage using a weaponskill while Swiftcast was in effect so it's possible the behavior has changed. It will be something to test once 4.0 goes live.

This is a bug, and will be fixed. Thank you!

> Also a couple related observations that would need verification to determine if they are issues. If you have both Dualcast and Swiftcast active when executing a weaponskill, Swiftcast will fade while Dualcast remains which seemed a little strange. The same behavior will happen if you have Dualcast and Swiftcast active upon the casting of a spell, consuming Swiftcast while leaving Dualcast in effect for use with another spell, but that could be an indented interaction.

And this is an intended interaction. I coded it that way, under the assumption that AST's old Enhanced Benefic proc worked the same way.

**Comment by CatXIV** [comment]
> And this is an intended interaction. I coded it that way, under the assumption that AST's old Enhanced Benefic proc worked the same way.

Oh I completely forgot about the old Enhanced Benefic proc. Good to know!

**Comment by Tylian** [comment]
Fixed this in 2b98c7c44c53c7c9a7d178da4bd13345fb4d8b34 (plus another small tweak I forgot I did whoops). Thanks!
