### ISSUE TITLE
Melee range

### ISSUE THREAD

**Issue by Awkwerp** [Tylian/rdm#5]
The new position graphic is nice, but I can still execute melee skills from afar. I suggest adding a range limit on those so people have to use corps-a-corps.

**Comment by Awkwerp** [comment]
I think the way to fix this would just be adding 
useable() {
    return state.melee;
}
to riposte, zwerchhau, redoublement, and the enchanted versions.

**Comment by Tylian** [comment]
Not really a bug, more of a design decision. What's to stop you from just walking up and meleeing an enemy a bunch? Not much.

But I've been thinking of disabling it anyway, just so people wouldn't be confused by the visualization showing you as far away yet being able to hit it.

**Comment by Awkwerp** [comment]
fair enough. I figured if your character is far away it should disable but it's up to you whatever you feel is best

**Comment by Tylian** [comment]
I ended up doing what you said, so you'll see it disabled in a future commit. Currently doing a batch of features all in one go.
