### ISSUE TITLE
Manual Movement

### ISSUE THREAD

**Issue by Uryxia** [Tylian/rdm#8]
A lot of people have been saying (justifiably) that it doesn't make sense that the only way to close into melee range is via using Corps-a-Corps (and, on the flip side, for Displacement to be the only way to move away).  I understand that the melee skills were limited to only when you've closed into melee range, but I think with that restriction in place, it should be possible to manually move the character (since you'll be able to do so in the game itself).  I can imagine it would basically be as simple as copy-pasting Corps-a-Corps and Displacement and removing the cooldown and damage.  Attached are icons that fit the FF14 aesthetic that would most clearly communicate their intended purpose.
![leftarrowicon](https://user-images.githubusercontent.com/29296015/26960096-479a0a8a-4c9a-11e7-985f-34aa7561340a.png)
![rightarrowicon](https://user-images.githubusercontent.com/29296015/26960098-493a0142-4c9a-11e7-9094-47de24099a61.png)

**Comment by Tylian** [comment]
I'm going to close this because I implemented a solution in 9e512f2490d10dc522d485153072d3ecf581d9eb.

Hopefully this pleases people, but if not, please do reopen this and I'll try and think of something else!
